-- Temporary script to seed 200 random concerns
-- Run this in Supabase SQL Editor
-- WARNING: This is for testing only - delete the data after testing

-- This will insert 200 concerns for the first user in auth.users
-- If you want to insert for a specific user, replace the WHERE clause with:
-- WHERE email = 'your-email@example.com'

WITH user_data AS (
  SELECT id FROM auth.users LIMIT 1
)
INSERT INTO concerns (user_id, group_code, urgency, task, start_date, remarks, status, detailed_status, pic) 
SELECT u.id, v.* FROM user_data u, (VALUES
('T', 'Normal', 'Review budget proposal #1', NOW() - INTERVAL '15 days', 'Test data', 'New', '', 'Admin'),
('E', 'Urgent', 'Prepare monthly report #2', NOW() - INTERVAL '22 days', 'Test data', 'Preparing', 'For Starting', 'John'),
('F', 'Major', 'Schedule team meeting #3', NOW() - INTERVAL '8 days', 'Test data', 'Ongoing', 'In Progress', 'Jane'),
('S', 'EMERGENCY', 'Update documentation #4', NOW() - INTERVAL '45 days', 'Test data', 'For Delegating', '', 'Mike'),
('AH', 'Major Urgent', 'Fix server issues #5', NOW() - INTERVAL '3 days', 'Test data', 'New', '', 'Sarah'),
('I', 'Normal', 'Coordinate with vendors #6', NOW() - INTERVAL '30 days', 'Test data', 'For Update', '', 'Tom'),
('V', 'Urgent', 'Process purchase orders #7', NOW() - INTERVAL '12 days', 'Test data', 'Preparing', 'Pending', 'Lisa'),
('A', 'Major', 'Organize training session #8', NOW() - INTERVAL '28 days', 'Test data', 'Ongoing', 'Delayed', 'David'),
('L', 'EMERGENCY', 'Review security protocols #9', NOW() - INTERVAL '5 days', 'Test data', 'For Report', '', 'Emma'),
('W', 'Normal', 'Update website content #10', NOW() - INTERVAL '50 days', 'Test data', 'New', '', 'Chris'),
('O', 'Major Urgent', 'Prepare presentation slides #11', NOW() - INTERVAL '18 days', 'Test data', 'Preparing', 'For Designing', 'Admin'),
('R', 'Urgent', 'Conduct site inspection #12', NOW() - INTERVAL '35 days', 'Test data', 'Ongoing', 'For Finishing', 'John'),
('D', 'Major', 'Process reimbursements #13', NOW() - INTERVAL '7 days', 'Test data', 'For Approval', '', 'Jane'),
('T', 'EMERGENCY', 'Schedule maintenance #14', NOW() - INTERVAL '40 days', 'Test data', 'New', '', 'Mike'),
('E', 'Normal', 'Review contracts #15', NOW() - INTERVAL '25 days', 'Test data', 'For Download', '', 'Sarah'),
('F', 'Major Urgent', 'Coordinate event logistics #16', NOW() - INTERVAL '11 days', 'Test data', 'Preparing', 'For Canvassing', 'Tom'),
('S', 'Urgent', 'Update inventory records #17', NOW() - INTERVAL '33 days', 'Test data', 'Ongoing', 'Pending', 'Lisa'),
('AH', 'Major', 'Prepare newsletter #18', NOW() - INTERVAL '20 days', 'Test data', 'New', '', 'David'),
('I', 'EMERGENCY', 'Review applications #19', NOW() - INTERVAL '2 days', 'Test data', 'For Delegating', '', 'Emma'),
('V', 'Normal', 'Schedule interviews #20', NOW() - INTERVAL '48 days', 'Test data', 'Preparing', 'For Quotation', 'Chris'),
('A', 'Major Urgent', 'Process payroll #21', NOW() - INTERVAL '14 days', 'Test data', 'Ongoing', 'For Starting', 'Admin'),
('L', 'Urgent', 'Update employee records #22', NOW() - INTERVAL '27 days', 'Test data', 'For Update', '', 'John'),
('W', 'Major', 'Coordinate volunteers #23', NOW() - INTERVAL '9 days', 'Test data', 'New', '', 'Jane'),
('O', 'EMERGENCY', 'Plan outreach program #24', NOW() - INTERVAL '55 days', 'Test data', 'For Report', '', 'Mike'),
('R', 'Normal', 'Organize workshop #25', NOW() - INTERVAL '17 days', 'Test data', 'Preparing', 'For Demo', 'Sarah'),
('D', 'Major Urgent', 'Review proposals #26', NOW() - INTERVAL '38 days', 'Test data', 'Ongoing', 'In Progress', 'Tom'),
('T', 'Urgent', 'Update systems #27', NOW() - INTERVAL '6 days', 'Test data', 'For Approval', '', 'Lisa'),
('E', 'Major', 'Prepare training materials #28', NOW() - INTERVAL '42 days', 'Test data', 'New', '', 'David'),
('F', 'EMERGENCY', 'Conduct audit #29', NOW() - INTERVAL '23 days', 'Test data', 'For Download', '', 'Emma'),
('S', 'Normal', 'Process invoices #30', NOW() - INTERVAL '10 days', 'Test data', 'Preparing', 'Delayed', 'Chris'),
('AH', 'Major Urgent', 'Review budget proposal #31', NOW() - INTERVAL '31 days', 'Test data', 'Ongoing', 'For Problem Solving', 'Admin'),
('I', 'Urgent', 'Prepare monthly report #32', NOW() - INTERVAL '19 days', 'Test data', 'New', '', 'John'),
('V', 'Major', 'Schedule team meeting #33', NOW() - INTERVAL '44 days', 'Test data', 'For Delegating', '', 'Jane'),
('A', 'EMERGENCY', 'Update documentation #34', NOW() - INTERVAL '4 days', 'Test data', 'Preparing', 'For Presentation', 'Mike'),
('L', 'Normal', 'Fix server issues #35', NOW() - INTERVAL '52 days', 'Test data', 'Ongoing', 'Delayed', 'Sarah'),
('W', 'Major Urgent', 'Coordinate with vendors #36', NOW() - INTERVAL '16 days', 'Test data', 'For Update', '', 'Tom'),
('O', 'Urgent', 'Process purchase orders #37', NOW() - INTERVAL '36 days', 'Test data', 'New', '', 'Lisa'),
('R', 'Major', 'Organize training session #38', NOW() - INTERVAL '21 days', 'Test data', 'For Report', '', 'David'),
('D', 'EMERGENCY', 'Review security protocols #39', NOW() - INTERVAL '13 days', 'Test data', 'Preparing', 'Pending', 'Emma'),
('T', 'Normal', 'Update website content #40', NOW() - INTERVAL '47 days', 'Test data', 'Ongoing', 'For Finishing', 'Chris'),
('E', 'Major Urgent', 'Prepare presentation slides #41', NOW() - INTERVAL '26 days', 'Test data', 'For Approval', '', 'Admin'),
('F', 'Urgent', 'Conduct site inspection #42', NOW() - INTERVAL '8 days', 'Test data', 'New', '', 'John'),
('S', 'Major', 'Process reimbursements #43', NOW() - INTERVAL '39 days', 'Test data', 'For Download', '', 'Jane'),
('AH', 'EMERGENCY', 'Schedule maintenance #44', NOW() - INTERVAL '24 days', 'Test data', 'Preparing', 'For Starting', 'Mike'),
('I', 'Normal', 'Review contracts #45', NOW() - INTERVAL '11 days', 'Test data', 'Ongoing', 'In Progress', 'Sarah'),
('V', 'Major Urgent', 'Coordinate event logistics #46', NOW() - INTERVAL '49 days', 'Test data', 'New', '', 'Tom'),
('A', 'Urgent', 'Update inventory records #47', NOW() - INTERVAL '32 days', 'Test data', 'For Delegating', '', 'Lisa'),
('L', 'Major', 'Prepare newsletter #48', NOW() - INTERVAL '7 days', 'Test data', 'Preparing', 'For Designing', 'David'),
('W', 'EMERGENCY', 'Review applications #49', NOW() - INTERVAL '58 days', 'Test data', 'Ongoing', 'Pending', 'Emma'),
('O', 'Normal', 'Schedule interviews #50', NOW() - INTERVAL '15 days', 'Test data', 'For Update', '', 'Chris'),
('R', 'Major Urgent', 'Process payroll #51', NOW() - INTERVAL '41 days', 'Test data', 'New', '', 'Admin'),
('D', 'Urgent', 'Update employee records #52', NOW() - INTERVAL '29 days', 'Test data', 'For Report', '', 'John'),
('T', 'Major', 'Coordinate volunteers #53', NOW() - INTERVAL '5 days', 'Test data', 'Preparing', 'For Canvassing', 'Jane'),
('E', 'EMERGENCY', 'Plan outreach program #54', NOW() - INTERVAL '53 days', 'Test data', 'Ongoing', 'Delayed', 'Mike'),
('F', 'Normal', 'Organize workshop #55', NOW() - INTERVAL '18 days', 'Test data', 'For Approval', '', 'Sarah'),
('S', 'Major Urgent', 'Review proposals #56', NOW() - INTERVAL '37 days', 'Test data', 'New', '', 'Tom'),
('AH', 'Urgent', 'Update systems #57', NOW() - INTERVAL '22 days', 'Test data', 'For Download', '', 'Lisa'),
('I', 'Major', 'Prepare training materials #58', NOW() - INTERVAL '12 days', 'Test data', 'Preparing', 'For Quotation', 'David'),
('V', 'EMERGENCY', 'Conduct audit #59', NOW() - INTERVAL '46 days', 'Test data', 'Ongoing', 'For Starting', 'Emma'),
('A', 'Normal', 'Process invoices #60', NOW() - INTERVAL '34 days', 'Test data', 'New', '', 'Chris'),
('L', 'Major Urgent', 'Review budget proposal #61', NOW() - INTERVAL '9 days', 'Test data', 'For Delegating', '', 'Admin'),
('W', 'Urgent', 'Prepare monthly report #62', NOW() - INTERVAL '51 days', 'Test data', 'Preparing', 'For Demo', 'John'),
('O', 'Major', 'Schedule team meeting #63', NOW() - INTERVAL '27 days', 'Test data', 'Ongoing', 'In Progress', 'Jane'),
('R', 'EMERGENCY', 'Update documentation #64', NOW() - INTERVAL '14 days', 'Test data', 'For Update', '', 'Mike'),
('D', 'Normal', 'Fix server issues #65', NOW() - INTERVAL '43 days', 'Test data', 'New', '', 'Sarah'),
('T', 'Major Urgent', 'Coordinate with vendors #66', NOW() - INTERVAL '20 days', 'Test data', 'For Report', '', 'Tom'),
('E', 'Urgent', 'Process purchase orders #67', NOW() - INTERVAL '6 days', 'Test data', 'Preparing', 'Delayed', 'Lisa'),
('F', 'Major', 'Organize training session #68', NOW() - INTERVAL '56 days', 'Test data', 'Ongoing', 'For Problem Solving', 'David'),
('S', 'EMERGENCY', 'Review security protocols #69', NOW() - INTERVAL '30 days', 'Test data', 'For Approval', '', 'Emma'),
('AH', 'Normal', 'Update website content #70', NOW() - INTERVAL '16 days', 'Test data', 'New', '', 'Chris'),
('I', 'Major Urgent', 'Prepare presentation slides #71', NOW() - INTERVAL '45 days', 'Test data', 'For Download', '', 'Admin'),
('V', 'Urgent', 'Conduct site inspection #72', NOW() - INTERVAL '25 days', 'Test data', 'Preparing', 'For Presentation', 'John'),
('A', 'Major', 'Process reimbursements #73', NOW() - INTERVAL '10 days', 'Test data', 'Ongoing', 'Delayed', 'Jane'),
('L', 'EMERGENCY', 'Schedule maintenance #74', NOW() - INTERVAL '54 days', 'Test data', 'New', '', 'Mike'),
('W', 'Normal', 'Review contracts #75', NOW() - INTERVAL '33 days', 'Test data', 'For Delegating', '', 'Sarah'),
('O', 'Major Urgent', 'Coordinate event logistics #76', NOW() - INTERVAL '19 days', 'Test data', 'Preparing', 'Pending', 'Tom'),
('R', 'Urgent', 'Update inventory records #77', NOW() - INTERVAL '7 days', 'Test data', 'Ongoing', 'For Finishing', 'Lisa'),
('D', 'Major', 'Prepare newsletter #78', NOW() - INTERVAL '48 days', 'Test data', 'For Update', '', 'David'),
('T', 'EMERGENCY', 'Review applications #79', NOW() - INTERVAL '28 days', 'Test data', 'New', '', 'Emma'),
('E', 'Normal', 'Schedule interviews #80', NOW() - INTERVAL '13 days', 'Test data', 'For Report', '', 'Chris'),
('F', 'Major Urgent', 'Process payroll #81', NOW() - INTERVAL '50 days', 'Test data', 'Preparing', 'For Starting', 'Admin'),
('S', 'Urgent', 'Update employee records #82', NOW() - INTERVAL '26 days', 'Test data', 'Ongoing', 'In Progress', 'John'),
('AH', 'Major', 'Coordinate volunteers #83', NOW() - INTERVAL '11 days', 'Test data', 'For Approval', '', 'Jane'),
('I', 'EMERGENCY', 'Plan outreach program #84', NOW() - INTERVAL '59 days', 'Test data', 'New', '', 'Mike'),
('V', 'Normal', 'Organize workshop #85', NOW() - INTERVAL '35 days', 'Test data', 'For Download', '', 'Sarah'),
('A', 'Major Urgent', 'Review proposals #86', NOW() - INTERVAL '21 days', 'Test data', 'Preparing', 'For Designing', 'Tom'),
('L', 'Urgent', 'Update systems #87', NOW() - INTERVAL '4 days', 'Test data', 'Ongoing', 'Pending', 'Lisa'),
('W', 'Major', 'Prepare training materials #88', NOW() - INTERVAL '57 days', 'Test data', 'New', '', 'David'),
('O', 'EMERGENCY', 'Conduct audit #89', NOW() - INTERVAL '31 days', 'Test data', 'For Delegating', '', 'Emma'),
('R', 'Normal', 'Process invoices #90', NOW() - INTERVAL '17 days', 'Test data', 'Preparing', 'For Canvassing', 'Chris'),
('D', 'Major Urgent', 'Review budget proposal #91', NOW() - INTERVAL '44 days', 'Test data', 'Ongoing', 'Delayed', 'Admin'),
('T', 'Urgent', 'Prepare monthly report #92', NOW() - INTERVAL '23 days', 'Test data', 'For Update', '', 'John'),
('E', 'Major', 'Schedule team meeting #93', NOW() - INTERVAL '8 days', 'Test data', 'New', '', 'Jane'),
('F', 'EMERGENCY', 'Update documentation #94', NOW() - INTERVAL '52 days', 'Test data', 'For Report', '', 'Mike'),
('S', 'Normal', 'Fix server issues #95', NOW() - INTERVAL '29 days', 'Test data', 'Preparing', 'For Quotation', 'Sarah'),
('AH', 'Major Urgent', 'Coordinate with vendors #96', NOW() - INTERVAL '15 days', 'Test data', 'Ongoing', 'For Starting', 'Tom'),
('I', 'Urgent', 'Process purchase orders #97', NOW() - INTERVAL '42 days', 'Test data', 'For Approval', '', 'Lisa'),
('V', 'Major', 'Organize training session #98', NOW() - INTERVAL '24 days', 'Test data', 'New', '', 'David'),
('A', 'EMERGENCY', 'Review security protocols #99', NOW() - INTERVAL '9 days', 'Test data', 'For Download', '', 'Emma'),
('L', 'Normal', 'Update website content #100', NOW() - INTERVAL '55 days', 'Test data', 'Preparing', 'For Demo', 'Chris'),
('W', 'Major Urgent', 'Prepare presentation slides #101', NOW() - INTERVAL '32 days', 'Test data', 'Ongoing', 'In Progress', 'Admin'),
('O', 'Urgent', 'Conduct site inspection #102', NOW() - INTERVAL '18 days', 'Test data', 'New', '', 'John'),
('R', 'Major', 'Process reimbursements #103', NOW() - INTERVAL '5 days', 'Test data', 'For Delegating', '', 'Jane'),
('D', 'EMERGENCY', 'Schedule maintenance #104', NOW() - INTERVAL '47 days', 'Test data', 'Preparing', 'Delayed', 'Mike'),
('T', 'Normal', 'Review contracts #105', NOW() - INTERVAL '27 days', 'Test data', 'Ongoing', 'For Problem Solving', 'Sarah'),
('E', 'Major Urgent', 'Coordinate event logistics #106', NOW() - INTERVAL '12 days', 'Test data', 'For Update', '', 'Tom'),
('F', 'Urgent', 'Update inventory records #107', NOW() - INTERVAL '60 days', 'Test data', 'New', '', 'Lisa'),
('S', 'Major', 'Prepare newsletter #108', NOW() - INTERVAL '36 days', 'Test data', 'For Report', '', 'David'),
('AH', 'EMERGENCY', 'Review applications #109', NOW() - INTERVAL '20 days', 'Test data', 'Preparing', 'For Presentation', 'Emma'),
('I', 'Normal', 'Schedule interviews #110', NOW() - INTERVAL '3 days', 'Test data', 'Ongoing', 'Delayed', 'Chris'),
('V', 'Major Urgent', 'Process payroll #111', NOW() - INTERVAL '51 days', 'Test data', 'For Approval', '', 'Admin'),
('A', 'Urgent', 'Update employee records #112', NOW() - INTERVAL '30 days', 'Test data', 'New', '', 'John'),
('L', 'Major', 'Coordinate volunteers #113', NOW() - INTERVAL '16 days', 'Test data', 'For Download', '', 'Jane'),
('W', 'EMERGENCY', 'Plan outreach program #114', NOW() - INTERVAL '43 days', 'Test data', 'Preparing', 'Pending', 'Mike'),
('O', 'Normal', 'Organize workshop #115', NOW() - INTERVAL '25 days', 'Test data', 'Ongoing', 'For Finishing', 'Sarah'),
('R', 'Major Urgent', 'Review proposals #116', NOW() - INTERVAL '10 days', 'Test data', 'New', '', 'Tom'),
('D', 'Urgent', 'Update systems #117', NOW() - INTERVAL '56 days', 'Test data', 'For Delegating', '', 'Lisa'),
('T', 'Major', 'Prepare training materials #118', NOW() - INTERVAL '33 days', 'Test data', 'Preparing', 'For Starting', 'David'),
('E', 'EMERGENCY', 'Conduct audit #119', NOW() - INTERVAL '19 days', 'Test data', 'Ongoing', 'In Progress', 'Emma'),
('F', 'Normal', 'Process invoices #120', NOW() - INTERVAL '6 days', 'Test data', 'For Update', '', 'Chris'),
('S', 'Major Urgent', 'Review budget proposal #121', NOW() - INTERVAL '49 days', 'Test data', 'New', '', 'Admin'),
('AH', 'Urgent', 'Prepare monthly report #122', NOW() - INTERVAL '28 days', 'Test data', 'For Report', '', 'John'),
('I', 'Major', 'Schedule team meeting #123', NOW() - INTERVAL '14 days', 'Test data', 'Preparing', 'For Designing', 'Jane'),
('V', 'EMERGENCY', 'Update documentation #124', NOW() - INTERVAL '58 days', 'Test data', 'Ongoing', 'Pending', 'Mike'),
('A', 'Normal', 'Fix server issues #125', NOW() - INTERVAL '34 days', 'Test data', 'For Approval', '', 'Sarah'),
('L', 'Major Urgent', 'Coordinate with vendors #126', NOW() - INTERVAL '21 days', 'Test data', 'New', '', 'Tom'),
('W', 'Urgent', 'Process purchase orders #127', NOW() - INTERVAL '2 days', 'Test data', 'For Download', '', 'Lisa'),
('O', 'Major', 'Organize training session #128', NOW() - INTERVAL '53 days', 'Test data', 'Preparing', 'For Canvassing', 'David'),
('R', 'EMERGENCY', 'Review security protocols #129', NOW() - INTERVAL '31 days', 'Test data', 'Ongoing', 'Delayed', 'Emma'),
('D', 'Normal', 'Update website content #130', NOW() - INTERVAL '17 days', 'Test data', 'New', '', 'Chris'),
('T', 'Major Urgent', 'Prepare presentation slides #131', NOW() - INTERVAL '46 days', 'Test data', 'For Delegating', '', 'Admin'),
('E', 'Urgent', 'Conduct site inspection #132', NOW() - INTERVAL '26 days', 'Test data', 'Preparing', 'For Quotation', 'John'),
('F', 'Major', 'Process reimbursements #133', NOW() - INTERVAL '11 days', 'Test data', 'Ongoing', 'For Starting', 'Jane'),
('S', 'EMERGENCY', 'Schedule maintenance #134', NOW() - INTERVAL '57 days', 'Test data', 'For Update', '', 'Mike'),
('AH', 'Normal', 'Review contracts #135', NOW() - INTERVAL '35 days', 'Test data', 'New', '', 'Sarah'),
('I', 'Major Urgent', 'Coordinate event logistics #136', NOW() - INTERVAL '22 days', 'Test data', 'For Report', '', 'Tom'),
('V', 'Urgent', 'Update inventory records #137', NOW() - INTERVAL '4 days', 'Test data', 'Preparing', 'For Demo', 'Lisa'),
('A', 'Major', 'Prepare newsletter #138', NOW() - INTERVAL '54 days', 'Test data', 'Ongoing', 'In Progress', 'David'),
('L', 'EMERGENCY', 'Review applications #139', NOW() - INTERVAL '29 days', 'Test data', 'For Approval', '', 'Emma'),
('W', 'Normal', 'Schedule interviews #140', NOW() - INTERVAL '15 days', 'Test data', 'New', '', 'Chris'),
('O', 'Major Urgent', 'Process payroll #141', NOW() - INTERVAL '41 days', 'Test data', 'For Download', '', 'Admin'),
('R', 'Urgent', 'Update employee records #142', NOW() - INTERVAL '24 days', 'Test data', 'Preparing', 'Delayed', 'John'),
('D', 'Major', 'Coordinate volunteers #143', NOW() - INTERVAL '9 days', 'Test data', 'Ongoing', 'For Problem Solving', 'Jane'),
('T', 'EMERGENCY', 'Plan outreach program #144', NOW() - INTERVAL '52 days', 'Test data', 'New', '', 'Mike'),
('E', 'Normal', 'Organize workshop #145', NOW() - INTERVAL '32 days', 'Test data', 'For Delegating', '', 'Sarah'),
('F', 'Major Urgent', 'Review proposals #146', NOW() - INTERVAL '18 days', 'Test data', 'Preparing', 'For Presentation', 'Tom'),
('S', 'Urgent', 'Update systems #147', NOW() - INTERVAL '7 days', 'Test data', 'Ongoing', 'Delayed', 'Lisa'),
('AH', 'Major', 'Prepare training materials #148', NOW() - INTERVAL '48 days', 'Test data', 'For Update', '', 'David'),
('I', 'EMERGENCY', 'Conduct audit #149', NOW() - INTERVAL '27 days', 'Test data', 'New', '', 'Emma'),
('V', 'Normal', 'Process invoices #150', NOW() - INTERVAL '13 days', 'Test data', 'For Report', '', 'Chris'),
('A', 'Major Urgent', 'Review budget proposal #151', NOW() - INTERVAL '59 days', 'Test data', 'Preparing', 'Pending', 'Admin'),
('L', 'Urgent', 'Prepare monthly report #152', NOW() - INTERVAL '37 days', 'Test data', 'Ongoing', 'For Finishing', 'John'),
('W', 'Major', 'Schedule team meeting #153', NOW() - INTERVAL '23 days', 'Test data', 'For Approval', '', 'Jane'),
('O', 'EMERGENCY', 'Update documentation #154', NOW() - INTERVAL '1 day', 'Test data', 'New', '', 'Mike'),
('R', 'Normal', 'Fix server issues #155', NOW() - INTERVAL '50 days', 'Test data', 'For Download', '', 'Sarah'),
('D', 'Major Urgent', 'Coordinate with vendors #156', NOW() - INTERVAL '30 days', 'Test data', 'Preparing', 'For Starting', 'Tom'),
('T', 'Urgent', 'Process purchase orders #157', NOW() - INTERVAL '16 days', 'Test data', 'Ongoing', 'In Progress', 'Lisa'),
('E', 'Major', 'Organize training session #158', NOW() - INTERVAL '45 days', 'Test data', 'New', '', 'David'),
('F', 'EMERGENCY', 'Review security protocols #159', NOW() - INTERVAL '25 days', 'Test data', 'For Delegating', '', 'Emma'),
('S', 'Normal', 'Update website content #160', NOW() - INTERVAL '12 days', 'Test data', 'Preparing', 'For Designing', 'Chris'),
('AH', 'Major Urgent', 'Prepare presentation slides #161', NOW() - INTERVAL '55 days', 'Test data', 'Ongoing', 'Pending', 'Admin'),
('I', 'Urgent', 'Conduct site inspection #162', NOW() - INTERVAL '33 days', 'Test data', 'For Update', '', 'John'),
('V', 'Major', 'Process reimbursements #163', NOW() - INTERVAL '19 days', 'Test data', 'New', '', 'Jane'),
('A', 'EMERGENCY', 'Schedule maintenance #164', NOW() - INTERVAL '6 days', 'Test data', 'For Report', '', 'Mike'),
('L', 'Normal', 'Review contracts #165', NOW() - INTERVAL '44 days', 'Test data', 'Preparing', 'For Canvassing', 'Sarah'),
('W', 'Major Urgent', 'Coordinate event logistics #166', NOW() - INTERVAL '28 days', 'Test data', 'Ongoing', 'Delayed', 'Tom'),
('O', 'Urgent', 'Update inventory records #167', NOW() - INTERVAL '14 days', 'Test data', 'For Approval', '', 'Lisa'),
('R', 'Major', 'Prepare newsletter #168', NOW() - INTERVAL '60 days', 'Test data', 'New', '', 'David'),
('D', 'EMERGENCY', 'Review applications #169', NOW() - INTERVAL '38 days', 'Test data', 'For Download', '', 'Emma'),
('T', 'Normal', 'Schedule interviews #170', NOW() - INTERVAL '21 days', 'Test data', 'Preparing', 'For Quotation', 'Chris'),
('E', 'Major Urgent', 'Process payroll #171', NOW() - INTERVAL '3 days', 'Test data', 'Ongoing', 'For Starting', 'Admin'),
('F', 'Urgent', 'Update employee records #172', NOW() - INTERVAL '51 days', 'Test data', 'New', '', 'John'),
('S', 'Major', 'Coordinate volunteers #173', NOW() - INTERVAL '31 days', 'Test data', 'For Delegating', '', 'Jane'),
('AH', 'EMERGENCY', 'Plan outreach program #174', NOW() - INTERVAL '17 days', 'Test data', 'Preparing', 'For Demo', 'Mike'),
('I', 'Normal', 'Organize workshop #175', NOW() - INTERVAL '47 days', 'Test data', 'Ongoing', 'In Progress', 'Sarah'),
('V', 'Major Urgent', 'Review proposals #176', NOW() - INTERVAL '26 days', 'Test data', 'For Update', '', 'Tom'),
('A', 'Urgent', 'Update systems #177', NOW() - INTERVAL '11 days', 'Test data', 'New', '', 'Lisa'),
('L', 'Major', 'Prepare training materials #178', NOW() - INTERVAL '56 days', 'Test data', 'For Report', '', 'David'),
('W', 'EMERGENCY', 'Conduct audit #179', NOW() - INTERVAL '34 days', 'Test data', 'Preparing', 'Delayed', 'Emma'),
('O', 'Normal', 'Process invoices #180', NOW() - INTERVAL '20 days', 'Test data', 'Ongoing', 'For Problem Solving', 'Chris'),
('R', 'Major Urgent', 'Review budget proposal #181', NOW() - INTERVAL '8 days', 'Test data', 'For Approval', '', 'Admin'),
('D', 'Urgent', 'Prepare monthly report #182', NOW() - INTERVAL '53 days', 'Test data', 'New', '', 'John'),
('T', 'Major', 'Schedule team meeting #183', NOW() - INTERVAL '29 days', 'Test data', 'For Download', '', 'Jane'),
('E', 'EMERGENCY', 'Update documentation #184', NOW() - INTERVAL '15 days', 'Test data', 'Preparing', 'For Presentation', 'Mike'),
('F', 'Normal', 'Fix server issues #185', NOW() - INTERVAL '42 days', 'Test data', 'Ongoing', 'Delayed', 'Sarah'),
('S', 'Major Urgent', 'Coordinate with vendors #186', NOW() - INTERVAL '24 days', 'Test data', 'New', '', 'Tom'),
('AH', 'Urgent', 'Process purchase orders #187', NOW() - INTERVAL '10 days', 'Test data', 'For Delegating', '', 'Lisa'),
('I', 'Major', 'Organize training session #188', NOW() - INTERVAL '58 days', 'Test data', 'Preparing', 'Pending', 'David'),
('V', 'EMERGENCY', 'Review security protocols #189', NOW() - INTERVAL '36 days', 'Test data', 'Ongoing', 'For Finishing', 'Emma'),
('A', 'Normal', 'Update website content #190', NOW() - INTERVAL '22 days', 'Test data', 'For Update', '', 'Chris'),
('L', 'Major Urgent', 'Prepare presentation slides #191', NOW() - INTERVAL '5 days', 'Test data', 'New', '', 'Admin'),
('W', 'Urgent', 'Conduct site inspection #192', NOW() - INTERVAL '49 days', 'Test data', 'For Report', '', 'John'),
('O', 'Major', 'Process reimbursements #193', NOW() - INTERVAL '27 days', 'Test data', 'Preparing', 'For Starting', 'Jane'),
('R', 'EMERGENCY', 'Schedule maintenance #194', NOW() - INTERVAL '13 days', 'Test data', 'Ongoing', 'In Progress', 'Mike'),
('D', 'Normal', 'Review contracts #195', NOW() - INTERVAL '40 days', 'Test data', 'For Approval', '', 'Sarah'),
('T', 'Major Urgent', 'Coordinate event logistics #196', NOW() - INTERVAL '23 days', 'Test data', 'New', '', 'Tom'),
('E', 'Urgent', 'Update inventory records #197', NOW() - INTERVAL '9 days', 'Test data', 'For Download', '', 'Lisa'),
('F', 'Major', 'Prepare newsletter #198', NOW() - INTERVAL '54 days', 'Test data', 'Preparing', 'For Designing', 'David'),
('S', 'EMERGENCY', 'Review applications #199', NOW() - INTERVAL '32 days', 'Test data', 'Ongoing', 'Pending', 'Emma'),
('AH', 'Normal', 'Schedule interviews #200', NOW() - INTERVAL '18 days', 'Test data', 'New', '', 'Chris')
) AS v(group_code, urgency, task, start_date, remarks, status, detailed_status, pic);

-- Verify the insert
SELECT COUNT(*) as total_concerns FROM concerns;
